# Generated by Django 4.2.7 on 2023-11-21 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("vpn", "0002_vpnstats_delete_useractivity"),
    ]

    operations = [
        migrations.CreateModel(
            name="VpnUsageStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_url", models.URLField()),
                ("page_transitions", models.IntegerField(default=0)),
                ("data_sent", models.BigIntegerField(default=0)),
                ("data_received", models.BigIntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="VPNStats",
        ),
    ]
